[project]
name = "2rue-linear"
revision = "1.0"

[providers]
personal = "onepassword://Personal"

[profiles.default]
LINEAR_API_TOKEN = { description = "Linear token to access API", required = true, ref = { item = "linear-personal-project", field = "token"}, providers = ["personal"], credentials = { service_account_token = "keyring" }}
